DWAPlannerROS:
  dwa: true
  
  max_vel_x: 0.5
  max_vel_y: 0.0
  min_vel_x: -0.5

  max_rot_vel: 2
  min_rot_vel: 0.3

  acc_lim_th: 1
  acc_lim_x: 0.5

  yaw_goal_tolerance: .05
  xy_goal_tolerance: .1

  goal_distance_bias: 32
  path_distance_bias: 64
  occdist_scale: 0.1

  
  sim_time: 1.5

  
  holonomic_robot: false
