DWAPlannerROS:
  dwa: true
  
  max_vel_x: 0.1
  max_vel_y: 0.0
  min_vel_y: 0.0
  min_vel_x: 0.020

  max_rot_vel: 0.2
  min_rot_vel: 0.1
  escape_vel: -0.04

  acc_lim_th: 0.05
  acc_lim_x: 0.005

  yaw_goal_tolerance: .1
  xy_goal_tolerance: .1

  goal_distance_bias: 32
  path_distance_bias: 24
  occdist_scale: 0.05

  
  sim_time: 1
  
  holonomic_robot: false

  prune_plan: true
