TrajectoryPlannerROS:

    max_vel_x: 0.1
    min_vel_x: 0.05
    escape_vel: -0.05
    
    max_vel_theta: 1.0
    min_vel_theta: 0.1
    min_in_place_vel_theta: 0.25

    acc_lim_x: 0.05
    acc_lim_y: 0.0
    acc_lim_theta: 0.05
    acc_lim_th: 0.1

    xy_goal_tolerance: 0.10
    yaw_goal_tolerance: 0.1

    holonomic_robot: false

    sim_time: 0.6
    vx_samples: 5
    vtheta_samples: 15
    sim_granularity: 0.05

    pdist_scale: 0.6
    gdist_scale: 0.8

    occdist_scale: 0.075
    heading_lookahead: 0.2
    heading_scoring: false

    dwa: true
