DWAPlannerROS:
  dwa: true
  
  max_vel_x: 0.08
  max_vel_y: 0.0
  min_vel_y: 0.0
  min_vel_x: 0.02

  max_rot_vel: 0.3
  min_rot_vel: 0.15

  acc_lim_th: 0.1
  acc_lim_x: 0.025

  yaw_goal_tolerance: .1
  xy_goal_tolerance: .1

  goal_distance_bias: 24
  path_distance_bias: 36
  occdist_scale: 0.075

  
  sim_time: 3
  sim_grannularity: 0.05


  holonomic_robot: false

  
