DWAPlannerROS:
  dwa: true
  
  max_vel_x: 0.08
  max_vel_y: 0.0
  min_vel_y: 0.0
  min_vel_x: -0.04

  max_rot_vel: 0.5
  min_rot_vel: 0.15

  acc_lim_th: 0.5
  acc_lim_x: 0.04

  yaw_goal_tolerance: .1
  xy_goal_tolerance: .1

  goal_distance_bias: 32
  path_distance_bias: 64
  occdist_scale: 2

  
  sim_time: 1

  
  holonomic_robot: false
