TrajectoryPlannerROS:
 max_vel_x: 0.2
 min_vel_x: 0.05
 max_vel_y: 0.0
 min_vel_y: 0.0

 max_vel_theta: 2.0
 min_vel_theta: -2.0
 min_in_place_vel_theta: 1.0

 escape_vel: -0.05

 acc_lim_theta: 0.05
 acc_lim_x: 0.05


 yaw_goal_tolerance: 0.1
 xy_goal_tolerance: 0.10

 sim_time: 1.5
 sim_granularity: 0.025
 vx_sample: 6
 vy_samples: 0
 vtheta_samples: 20

 meter_scoring: true
 pdist_scale: 0.8
 gdist_scale: 0.6
 occdist_scale: 0.02
 heading_scoring: false
 heading_lookahead: 0.2

 dwa: false

 holonomic_robot: false
 
