TrajectoryPlannerROS:

    max_vel_x: 0.3
    min_vel_x: 0.1
    escape_vel: -0.1
    
    max_vel_theta: 2.0
    min_vel_theta: 0.125
    min_in_place_vel_theta: 1.0

    acc_lim_x: 0.1
    acc_lim_y: 0.0
    acc_lim_theta: 0.5
    acc_lim_th: 0.5

    xy_goal_tolerance: 0.10
    yaw_goal_tolerance: 0.05

    holonomic_robot: false

    sim_time: 1.5
    vx_samples: 8
    vtheta_samples: 20
    sim_granularity: 0.05

    pdist_scale: 0.6
    gdist_scale: 1.0

    occdist_scale: 0.1
    heading_lookahead: 0.1
    heading_scoring: false

    dwa: true
