TrajectoryPlannerROS:

    max_vel_x: 0.2
    min_vel_x: -0.2
    
    max_vel_theta: 1.0
    min_vel_theta: -1.0

    acc_lim_x: 0.1
    acc_lim_y: 0.0
    acc_lim_theta: 0.5

    xy_goal_tolerance: 0.10
    yaw_goal_tolerance: 0.05

    holonomic_robot: false

    sim_time: 0.8
    vx_samples: 18
    vtheta_samples: 20
    sim_granularity: 0.05
