DWAPlannerROS:
  dwa: true
  
  max_vel_x: 0.1
  max_vel_y: 0.0
  min_vel_y: 0.0
  min_vel_x: -0.05

  max_rot_vel: 0.3
  min_rot_vel: 0.1

  acc_lim_th: 0.3
  acc_lim_x: 0.05

  yaw_goal_tolerance: .1
  xy_goal_tolerance: .1

  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.5

  
  sim_time: 5
  
  holonomic_robot: false
