DWAPlannerROS:
  dwa: true
  
  max_vel_x: 0.25
  max_vel_y: 0.0
  min_vel_y: 0.0
  min_vel_x: -0.01

  max_rot_vel: 0.5
  min_rot_vel: 0.3

  acc_lim_th: 1
  acc_lim_x: 0.25

  yaw_goal_tolerance: .1
  xy_goal_tolerance: .1

  goal_distance_bias: 32
  path_distance_bias: 64
  occdist_scale: 2

  
  sim_time: 2

  
  holonomic_robot: false
