TrajectoryPlannerROS:
  dwa: true
  
  max_vel_x: 0.5
  max_vel_y: 0.0
  min_vel_x: -0.5

  max_rot_vel: 1
  min_rot_vel: 0.2

  acc_lim_th: 0.5
  acc_lim_x: 0.25

  yaw_goal_tolerance: .05
  xy_goal_tolerance: .1

  goal_distance_bias: 15
  path_distance_bias: 100
  occdist_scale: 64
  
  sim_time: 2.5

  
  holonomic_robot: false
