DWAPlannerROS:
  dwa: true
  
  max_vel_x: 0.05
  max_vel_y: 0.0
  min_vel_y: 0.0
  min_vel_x: 0.015

  max_rot_vel: 0.2
  min_rot_vel: 0.1

  acc_lim_th: 0.2
  acc_lim_x: 0.05

  yaw_goal_tolerance: .1
  xy_goal_tolerance: .1

  goal_distance_bias: 32
  path_distance_bias: 64
  occdist_scale: 0.5

  
  sim_time: 5

  
  holonomic_robot: false
