TrajectoryPlannerROS:

    max_vel_x: 0.2
    min_vel_x: 0.05
    escape_vel: -0.1
    
    max_vel_theta: 1.0
    min_vel_theta: 0.25
    min_in_place_vel_theta: 0.5

    acc_lim_x: 0.1
    acc_lim_y: 0.0
    acc_lim_theta: 0.25

    xy_goal_tolerance: 0.10
    yaw_goal_tolerance: 0.05

    holonomic_robot: false

    sim_time: 5
    vx_samples: 5
    vtheta_samples: 20
    sim_granularity: 0.1

    pdist_scale: 1.5
    gdist_scale: 0.6

    occdist_scale: 0.1
    heading_lookahead: 0.1
    heading_scoring: false

    dwa: true
