obstacle_range: 1.25
raytrace_range: 1.25
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
footprint: [[0.10, -0.125], [-0.2,-0.125], [-0.2, 0.125], [0.10, 0.125]]
inflation_radius: 0.1

observation_sources: laser_scan_sensor #point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /sweeper/scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
