map_type: ObstacleLayer

obstacle_range: 1.000
raytrace_range: 1.250

inf_is_valid: true

footprint: [[0.10, -0.125], [-0.2,-0.125], [-0.2, 0.125], [0.10, 0.125]]
footprint_padding: 0.005

inflation_radius: 0.3
cost_scaling_factor: 5
lethal_cost_threshold: 100

observation_sources: laser_scan_sensor #point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
