DWAPlannerROS:

    acc_lim_x: 0.1
    acc_lim_y: 0.0
    acc_lim_th: 1.0

    max_trans_vel: 0.2
    max_vel_x: 0.2
    min_vel_x: -0.2
    max_vel_y: 0.0
    min_vel_y: 0.0
    max_rot_vel: 1.0
    min_rot_vel: 0.4

    yaw_goal_tolerance: 0.05
    xy_goal_tolerance: 0.1

    sim_time: 2.0
    vx_samples: 20
    vy_samples: 0
    vtheta_samples: 40

    path_distance_bias: 32.0
    goal_distance_bias: 24.0
    occdist_scale: 0.04
    forward_point_distance: 0.05
    stop_time_buffer: 0.2
    scaling speed: 0.25
    max_scaling_factor: 0.2

    oscillation_reset_dist: 0.05

    publish_traj_pc: true
    publish_cost_grid_pc: true
