# static_map - True if using existing map

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1
  publish_frequency: 0.25
  resolution: 0.05
  static_map: true
  width: 4
  height: 4
