# static_map - True if using existing map

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1
  publish_frequency: 0.5
  resolution: 0.1
  static_map: true
  width: 15.0
  height: 15.0
