local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 1
  height: 1
  resolution: 0.04
  origin_x: 0.0
  prigin_y: 0.0
