<?xml version='1.0'?>

<robot name="rosie" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  
  <xacro:property name="PI" value="3.1415926535897931"/>
  
  <xacro:property name="chassisHeight" value="0.060"/>
  <xacro:property name="chassisWidth" value="0.240"/>
  <xacro:property name="chassisLength" value="0.3"/>
  <xacro:property name="chassisMass" value="4"/>
  <xacro:property name="groundClearance" value="0.01"/>
  
  <xacro:property name="casterRadius" value="0.02"/>
  <xacro:property name="casterMass" value="0.025"/>
  
  <xacro:property name="wheelRadius" value="0.030"/>
  <xacro:property name="wheelWidth" value="0.025"/>  
  <xacro:property name="wheelBase" value="0.185"/>
  <xacro:property name="wheelMass" value="0.05"/>  
  
  <xacro:include filename="$(find rosie_description)/urdf/rosie.gazebo" />
  <xacro:include filename="$(find rosie_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find rosie_description)/urdf/macros.xacro" />


  <link name='base_link'>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>

    <visual name='base_link_visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </visual>
  </link>
  
  
  <link name="caster_wheel"> 
    <collision>   
      <origin xyz="-0.125 0 ${casterRadius-(chassisHeight/2+groundClearance)}" rpy="0 0 0"/>
      <geometry> 
        <sphere radius="${casterRadius}"/> 
      </geometry> 
    </collision> 

    <visual> 
      <origin xyz="-0.125 0 ${casterRadius-(chassisHeight/2+groundClearance)}" rpy="0 0 0"/>
      <geometry> 
        <sphere radius="${casterRadius}"/> 
      </geometry> 
    </visual> 

    <inertial>
      <origin xyz="-0.125 0 ${casterRadius-(chassisHeight/2+groundClearance)}" rpy="0 0 0"/>
        <mass value="${casterMass}"/> 
      <sphere_inertia m="${casterMass}" r="${casterRadius}"/> 
    </inertial> 
  </link>


  <joint type="fixed" name="caster_wheel_joint">
    <child link="caster_wheel"/>
    <parent link="base_link"/>
  </joint>

  <wheel lr="left" tY="1"/> 
  <wheel lr="right" tY="-1"/>
  
  

<!-- Hokuyo Laser -->
  <link name="hokuyo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rosie_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <!--axis xyz="0 1 0" />-->
    <origin xyz=".07 0 .06" rpy="0 0 -0.698132"/>
    <parent link="base_link"/>
    <child link="hokuyo"/>
  </joint>


<!-- IMU -->
  <link name="imu_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
	
  <joint name="imu_joint" type="fixed">
    <origin xyz="0.08 0.050 -0.01" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="imu_link"/>
  </joint>


</robot>

